### PR TITLE
Use `rbac.authorization.k8s.io/v1` for metric-reader ClusterRole

### LINKED ISSUE #22: deprecation of rbac.authorization.k8s.io/v1beta1
We would need to upgrade our EKS version to `1.17` from `1.16` which deprecates `rbac.authorization.k8s.io/v1beta1` , we found [relevances](https://github.com/foriequal0/pod-graceful-drain/blob/main/config/rbac/auth_proxy_client_clusterrole.yaml) to it in your code but could not completely understand if they are actively being used in the project.
Could you confirm if these would be upgraded in the near future since we might move to `EKS 1.21` in the coming months.

### PR DESCRIPTION
**Pull request by ajaykumarmandapati**
We would need to upgrade our EKS version to 1.17 from 1.16 which deprecates rbac.authorization.k8s.io/v1beta1 , we found relevances to it in your code but could not completely understand if they are actively being used in the project.

Hey, I made the relevant changes in the API and then ran `make generate`. Thanks!

### CODE REVIEW

**Review by foriequal0 — CHANGES_REQUESTED** [review]
I think the only change that we need is `config/rbac/auth_rpoxy_client_clusterrole.yaml`. Can you amend the commit so it only contains the change that we need?

**Comment by foriequal0** [comment]
Thanks. Can you do it again for `go.sum` too? I want you to rebase the branch so it contain only 1 commit.

**Comment by foriequal0** [comment]
Thank you!

**Review by foriequal0 — APPROVED** [review]

**Comment by ajaykumarmandapati** [comment]
Hello! @foriequal0 Could you let us know the `release mechanism` for this version ? we would like to upgrade our `PGD` to this version.

**Comment by foriequal0** [comment]
I only manage versions of binary, and Helm template. I don't manage version of kustomize manifests under `config/`. You just download kustomize manifests to your project and deploy them.

**Pull request merged**
